import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { Box, Button, Progress, Text } from '@chakra-ui/react';
import DropzoneArea from 'components/DropzoneArea';
import { useState } from 'react';
import axios, { AxiosRequestConfig } from 'axios';

export default function Home() {
  const [files, setFiles] = useState<File[]>([]);

  const [tokopedia, setTokopedia] = useState<File>();
  const [shopee, setShopee] = useState<File>();
  const [lazada, setLazada] = useState<File>();

  const [uploadErrorMessage, setUploadErrorMessage] = useState<string>('');
  const [progress, setProgress] = useState<number>(0);

  const config: AxiosRequestConfig = {
    headers: { 'content-type': 'multipart/form-data' },
    onUploadProgress: (event: any) => {
      setProgress(Math.round((event.loaded * 100) / event.total));
    },
    responseType: 'blob',
  };

  const uploadFiles = async () => {
    setProgress(0);
    setUploadErrorMessage('');

    try {
      const formData = new FormData();

      Array.from(files).forEach((file) => {
        formData.append('base', file);
      });
      if (tokopedia) formData.append('tokopedia', tokopedia);
      if (shopee) formData.append('shopee', shopee);
      if (lazada) formData.append('lazada', lazada);

      const result = await axios.post('/api/uploads', formData, config);

      const url = window.URL.createObjectURL(new Blob([result.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'file.zip'); //or any other extension
      document.body.appendChild(link);
      link.click();
    } catch (error) {
      console.log(error, 'error client');

      setUploadErrorMessage(
        'There was an error with the upload. Please contact the developer for more info.'
      );
    }
  };

  return (
    <Box className={styles.container}>
      <Head>
        <title>Watermark Applier</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Box
          display={'flex'}
          justifyContent={'space-between'}
          width={'full'}
          gap={8}
        >
          <Box flex={1}>
            <Text>Tokopedia watermark</Text>
            <DropzoneArea onChange={(values) => setTokopedia(values[0])} />
          </Box>

          <Box flex={1}>
            <Text>Shopee watermark</Text>
            <DropzoneArea onChange={(values) => setShopee(values[0])} />
          </Box>

          <Box flex={1}>
            <Text>Lazada watermark</Text>
            <DropzoneArea onChange={(values) => setLazada(values[0])} />
          </Box>
        </Box>

        <Box width={'full'} mt={4}>
          <Text>Images to be watermarked</Text>
          <DropzoneArea multiple onChange={(values) => setFiles(values)} />
        </Box>

        {progress > 0 && (
          <Box width={'full'} mt={4}>
            <Progress value={progress} hasStripe />
          </Box>
        )}

        {uploadErrorMessage && (
          <Box width={'full'} mt={4}>
            <Text color={'red'}>{uploadErrorMessage}</Text>
          </Box>
        )}

        <Button
          mt={4}
          disabled={(!tokopedia || !shopee || !lazada) && files.length === 0}
          onClick={uploadFiles}
        >
          Apply watermark and download
        </Button>
      </main>
    </Box>
  );
}
